### PR TITLE
Unpublished pages should return 404

### PR DESCRIPTION
**Pull request by mamfi-0221**
1. If a page was `unpublished` from the studio or a page was created (at least the title + slug, may or may not have components added) but was `never published`
    - LIVE or draft pages should return 404 (you have to publish the page again to preview real-time and LIVE changes)
    - Page should not be found on the sitemap.xml
    
2. If a page was `published` then has `unpublished edits`
    - LIVE page should return the last published preview
    - Web preview/inline editing should return ALL the unpublished edits
    - Page should be found on the sitemap.xml

3. If the page was `published` 
    - LIVE and draft page should return the current published preview
    - Page should be found on the sitemap.xml

### CODE REVIEW

**Comment by webriq** [comment]
Hello @mamfi-0221 , let's try to see if we can utilize [Sanity Perspectives](https://www.sanity.io/docs/perspectives) here. See sample implementation here: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/32714f89607d1f08400888b728700ad5eb52883d/lib/sanity.client.ts#L19-L43

**Review by webriq — CHANGES_REQUESTED** [review]
Please find previous comment about Sanity Perspectives

**Comment by mamfi-0221** [comment]
Hello, thanks for reviewing! I have updated the implementation using sanity studio's "perspectives" on supported pages. I have also updated the pull request description with use cases that may help with testing. This is ready for review.

**Review by webriq — COMMENTED** [review]
Does it make sense to not throw 404 in `/` if there is no page published? If I remember correctly, it shows a blank white page.

image

**Review by webriq — CHANGES_REQUESTED** [review]
Upon contemplating, I think it makes sense now and while we're here to correct the behaviors as such:

1. Draft and/or unpublished will always show content when in preview mode.
2. Unpublished and deleted pages will return 404 on LIVE setting
3. Draft will show last content that was published in LIVE
4. Draft will show latest content when in preview mode.
5. Deleted documents will become 404 as soon as they get deleted.

**Comment by mamfi-0221** [comment]
Closing this pull request in favor of #252 where all commits should be for the correct behavior per last review. Thanks!

**Pull request closed without merging**
